### PR TITLE
feat: ability to add tasks

### LINKED ISSUE #27: Add ability to add tasks
**Is your feature request related to a problem? Please describe.**
We need the ability to add tasks

**Describe the solution you'd like**
Use jquery in handling the add task input. Input should be checked, empty input is not allowed. Use Materialize toast for event messages. Use the method provided in adding the tasks, it is already in the code any you only have to call it to add the said task. Aside from adding make sure to refresh the list of uncompleted todos to reflect the added task. Use minimal, simple and straighforward logic as possible. If possible to decouple functions, you may do so.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by abhinandansharma**
Fix: #27 
Features in the PR:
1) User can press enter or click the submit button to add new tasks.
2) Added materialize toasts for task addition
3) Input field will be erased after the task is added
4) If user presses Enter or clicks submit button and the input field is empty, no task will be added.

### CODE REVIEW

**Comment by andresitodeguzman** [comment]
PR almost ok except for issues stated below.

Issues seen while testing:

Issue 1: The first character of the previous entry is added on subsequent empty enter. Submit button still works even when the input field is empty
How to replicate:
1. Reload page/make sure page is newly loaded 
2. Type "Hello World"
2. Press enter
3. Press the submit button

Issue 2: Uncaught TypeError: M.Toast.dismiss is not a function
How to replicate:
1. Use the add task interface to add any.
2. Check console log

Possible solution: 
1. Get instance of the toast. (Code from https://materializecss.com/toasts.html)
```
 var toastElement = document.querySelector('.toast');
 var toastInstance = M.Toast.getInstance(toastElement);
 toastInstance.dismiss();
```
2. Close all toasts. (Code from https://materializecss.com/toasts.html)
```
M.Toast.dismissAll();
```

Would also recommend encapsulating the business logic (check if empty etc.) in a function and separating the key listener/button listener from the data check and insertion.

**Comment by abhinandansharma** [comment]
Alright, I'll fix it ASAP

**Comment by abhinandansharma** [comment]
I guess it's ready to merge now!

**Comment by andresitodeguzman** [comment]
You may view the deployed changes here: https://todo.pwapilipinas.org

**Pull request merged**
